// AUTO-GENERATED by LocatorCodegen — do NOT edit by hand.
// Re-run: npm run locators:generate
// Last updated: 2026-06-10T10:22:43.115Z
//
// Each entry is sourced from a Swift .accessibilityIdentifier("...") call.
// New entries (🆕) were added in the most recent codegen run.
// Review new entries and move intentional ones into FlowActions.ts when needed.
//
// Usage:
//   import { GL } from "./generated-locators.js";
//   await session.waitForDisplayed(GL.productCatalogHeader);

export const GL = {

  // ── Count ──────────────────────────────────────────────
  /** id: add_item_button | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/CountSheetsItemsView.swift 🆕 NEW */
  addItemButton: "~add_item_button",
  /** id: barcode_mode_button | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/CountSheetsItemsView.swift 🆕 NEW */
  barcodeModeButton: "~barcode_mode_button",
  /** id: cancel_button | src: Sources/ToastUnifiedInventory/Shared/UIComponents/SelectCountingStyleView.swift 🆕 NEW */
  cancelButton: "~cancel_button",
  /** id: count_item_card_\(item.id) | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/Components/CountItemCard.swift 🆕 NEW */
  countItemCard: "-ios predicate string:name BEGINSWITH \"count_item_card_\"",
  countItemCardFirst: '(//XCUIElementTypeOther[starts-with(@name, "count_item_card_")])[1]',
  countItemCardSecond: '(//XCUIElementTypeOther[starts-with(@name, "count_item_card_")])[2]',
  countItemCardNth: '(//XCUIElementTypeOther[starts-with(@name, "count_item_card_")])[{n}]',  // replace {n} with 1-based index
  /** id: counting_style_card_\(style.rawValue) | src: Sources/ToastUnifiedInventory/Shared/UIComponents/SelectCountingStyleView.swift 🆕 NEW */
  countingStyleCard: "-ios predicate string:name BEGINSWITH \"counting_style_card_\"",
  countingStyleCardFirst: '(//XCUIElementTypeOther[starts-with(@name, "counting_style_card_")])[1]',
  countingStyleCardSecond: '(//XCUIElementTypeOther[starts-with(@name, "counting_style_card_")])[2]',
  countingStyleCardNth: '(//XCUIElementTypeOther[starts-with(@name, "counting_style_card_")])[{n}]',  // replace {n} with 1-based index
  /** id: countingFieldView_\(item.id) | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/Components/CountingFieldView.swift 🆕 NEW */
  countingFieldView: "-ios predicate string:name BEGINSWITH \"countingFieldView_\"",
  countingFieldViewFirst: '(//XCUIElementTypeTextField[starts-with(@name, "countingFieldView_")])[1]',
  countingFieldViewSecond: '(//XCUIElementTypeTextField[starts-with(@name, "countingFieldView_")])[2]',
  countingFieldViewNth: '(//XCUIElementTypeTextField[starts-with(@name, "countingFieldView_")])[{n}]',  // replace {n} with 1-based index
  /** id: countInputSection_\(item.id) | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/Components/CountingFieldView.swift 🆕 NEW */
  countInputSection: "-ios predicate string:name BEGINSWITH \"countInputSection_\"",
  countInputSectionFirst: '(//XCUIElementTypeTextField[starts-with(@name, "countInputSection_")])[1]',
  countInputSectionSecond: '(//XCUIElementTypeTextField[starts-with(@name, "countInputSection_")])[2]',
  countInputSectionNth: '(//XCUIElementTypeTextField[starts-with(@name, "countInputSection_")])[{n}]',  // replace {n} with 1-based index
  /** id: countSheetName_\(countSheet.id) | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/CountSheetScreen.swift 🆕 NEW */
  countSheetName: "-ios predicate string:name BEGINSWITH \"countSheetName_\"",
  countSheetNameFirst: '(//XCUIElementTypeStaticText[starts-with(@name, "countSheetName_")])[1]',
  countSheetNameSecond: '(//XCUIElementTypeStaticText[starts-with(@name, "countSheetName_")])[2]',
  countSheetNameNth: '(//XCUIElementTypeStaticText[starts-with(@name, "countSheetName_")])[{n}]',  // replace {n} with 1-based index
  /** id: countSheetPickerEmptyState | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/CountSheetScreen.swift 🆕 NEW */
  countSheetPickerEmptyState: "~countSheetPickerEmptyState",
  /** id: countSheetTemplateRow_\(template.id) | src: Sources/ToastUnifiedInventory/Modules/CycleCount/CountSheetTemplates/Presentation/Views/CountSheetTemplateRow.swift 🆕 NEW */
  countSheetTemplateRow: "-ios predicate string:name BEGINSWITH \"countSheetTemplateRow_\"",
  countSheetTemplateRowFirst: '(//XCUIElementTypeOther[starts-with(@name, "countSheetTemplateRow_")])[1]',
  countSheetTemplateRowSecond: '(//XCUIElementTypeOther[starts-with(@name, "countSheetTemplateRow_")])[2]',
  countSheetTemplateRowNth: '(//XCUIElementTypeOther[starts-with(@name, "countSheetTemplateRow_")])[{n}]',  // replace {n} with 1-based index
  /** id: countSheetTemplateRow_applying_\(template.id) | src: Sources/ToastUnifiedInventory/Modules/CycleCount/CountSheetTemplates/Presentation/Views/CountSheetTemplateRow.swift 🆕 NEW */
  countSheetTemplateRowApplying: "-ios predicate string:name BEGINSWITH \"countSheetTemplateRow_applying_\"",
  countSheetTemplateRowApplyingFirst: '(//XCUIElementTypeOther[starts-with(@name, "countSheetTemplateRow_applying_")])[1]',
  countSheetTemplateRowApplyingSecond: '(//XCUIElementTypeOther[starts-with(@name, "countSheetTemplateRow_applying_")])[2]',
  countSheetTemplateRowApplyingNth: '(//XCUIElementTypeOther[starts-with(@name, "countSheetTemplateRow_applying_")])[{n}]',  // replace {n} with 1-based index
  /** id: countSheetTemplateRow_name_\(template.id) | src: Sources/ToastUnifiedInventory/Modules/CycleCount/CountSheetTemplates/Presentation/Views/CountSheetTemplateRow.swift 🆕 NEW */
  countSheetTemplateRowName: "-ios predicate string:name BEGINSWITH \"countSheetTemplateRow_name_\"",
  countSheetTemplateRowNameFirst: '(//XCUIElementTypeStaticText[starts-with(@name, "countSheetTemplateRow_name_")])[1]',
  countSheetTemplateRowNameSecond: '(//XCUIElementTypeStaticText[starts-with(@name, "countSheetTemplateRow_name_")])[2]',
  countSheetTemplateRowNameNth: '(//XCUIElementTypeStaticText[starts-with(@name, "countSheetTemplateRow_name_")])[{n}]',  // replace {n} with 1-based index
  /** id: countSheetTemplateRow_scheduledBadge_\(template.id) | src: Sources/ToastUnifiedInventory/Modules/CycleCount/CountSheetTemplates/Presentation/Views/CountSheetTemplateRow.swift 🆕 NEW */
  countSheetTemplateRowScheduledBadge: "-ios predicate string:name BEGINSWITH \"countSheetTemplateRow_scheduledBadge_\"",
  countSheetTemplateRowScheduledBadgeFirst: '(//XCUIElementTypeOther[starts-with(@name, "countSheetTemplateRow_scheduledBadge_")])[1]',
  countSheetTemplateRowScheduledBadgeSecond: '(//XCUIElementTypeOther[starts-with(@name, "countSheetTemplateRow_scheduledBadge_")])[2]',
  countSheetTemplateRowScheduledBadgeNth: '(//XCUIElementTypeOther[starts-with(@name, "countSheetTemplateRow_scheduledBadge_")])[{n}]',  // replace {n} with 1-based index
  /** id: countSheetTemplateRow_subtitle_\(template.id) | src: Sources/ToastUnifiedInventory/Modules/CycleCount/CountSheetTemplates/Presentation/Views/CountSheetTemplateRow.swift 🆕 NEW */
  countSheetTemplateRowSubtitle: "-ios predicate string:name BEGINSWITH \"countSheetTemplateRow_subtitle_\"",
  countSheetTemplateRowSubtitleFirst: '(//XCUIElementTypeStaticText[starts-with(@name, "countSheetTemplateRow_subtitle_")])[1]',
  countSheetTemplateRowSubtitleSecond: '(//XCUIElementTypeStaticText[starts-with(@name, "countSheetTemplateRow_subtitle_")])[2]',
  countSheetTemplateRowSubtitleNth: '(//XCUIElementTypeStaticText[starts-with(@name, "countSheetTemplateRow_subtitle_")])[{n}]',  // replace {n} with 1-based index
  /** id: countSheetTemplatesEmpty | src: Sources/ToastUnifiedInventory/Modules/CycleCount/CountSheetTemplates/Presentation/Views/CountSheetTemplatesListView.swift 🆕 NEW */
  countSheetTemplatesEmpty: "~countSheetTemplatesEmpty",
  /** id: countSheetTemplatesList | src: Sources/ToastUnifiedInventory/Modules/CycleCount/CountSheetTemplates/Presentation/Views/CountSheetTemplatesListView.swift 🆕 NEW */
  countSheetTemplatesList: "~countSheetTemplatesList",
  /** id: countSheetTemplatesListView | src: Sources/ToastUnifiedInventory/Modules/CycleCount/CountSheetTemplates/Presentation/Views/CountSheetTemplatesListView.swift 🆕 NEW */
  countSheetTemplatesListView: "~countSheetTemplatesListView",
  /** id: countSheetTemplatesLoading | src: Sources/ToastUnifiedInventory/Modules/CycleCount/CountSheetTemplates/Presentation/Views/CountSheetTemplatesListView.swift 🆕 NEW */
  countSheetTemplatesLoading: "~countSheetTemplatesLoading",
  /** id: countUnitLabel_\(item.id) | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/Components/CountingFieldView.swift 🆕 NEW */
  countUnitLabel: "-ios predicate string:name BEGINSWITH \"countUnitLabel_\"",
  countUnitLabelFirst: '(//XCUIElementTypeStaticText[starts-with(@name, "countUnitLabel_")])[1]',
  countUnitLabelSecond: '(//XCUIElementTypeStaticText[starts-with(@name, "countUnitLabel_")])[2]',
  countUnitLabelNth: '(//XCUIElementTypeStaticText[starts-with(@name, "countUnitLabel_")])[{n}]',  // replace {n} with 1-based index
  /** id: countUnitSection_\(item.id) | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/Components/CountingFieldView.swift 🆕 NEW */
  countUnitSection: "-ios predicate string:name BEGINSWITH \"countUnitSection_\"",
  countUnitSectionFirst: '(//XCUIElementTypeOther[starts-with(@name, "countUnitSection_")])[1]',
  countUnitSectionSecond: '(//XCUIElementTypeOther[starts-with(@name, "countUnitSection_")])[2]',
  countUnitSectionNth: '(//XCUIElementTypeOther[starts-with(@name, "countUnitSection_")])[{n}]',  // replace {n} with 1-based index
  /** id: dropdownLabel_\(text) | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/Components/CountingFieldView.swift 🆕 NEW */
  dropdownLabel: "-ios predicate string:name BEGINSWITH \"dropdownLabel_\"",
  dropdownLabelFirst: '(//XCUIElementTypeStaticText[starts-with(@name, "dropdownLabel_")])[1]',
  dropdownLabelSecond: '(//XCUIElementTypeStaticText[starts-with(@name, "dropdownLabel_")])[2]',
  dropdownLabelNth: '(//XCUIElementTypeStaticText[starts-with(@name, "dropdownLabel_")])[{n}]',  // replace {n} with 1-based index
  /** id: expandable_chevron_\(item.id) | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/Components/ExpandableCountItemCard.swift 🆕 NEW */
  expandableChevron: "-ios predicate string:name BEGINSWITH \"expandable_chevron_\"",
  expandableChevronFirst: '(//XCUIElementTypeImage[starts-with(@name, "expandable_chevron_")])[1]',
  expandableChevronSecond: '(//XCUIElementTypeImage[starts-with(@name, "expandable_chevron_")])[2]',
  expandableChevronNth: '(//XCUIElementTypeImage[starts-with(@name, "expandable_chevron_")])[{n}]',  // replace {n} with 1-based index
  /** id: expandable_countingFields_\(item.id) | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/Components/ExpandableCountItemCard.swift 🆕 NEW */
  expandableCountingFields: "-ios predicate string:name BEGINSWITH \"expandable_countingFields_\"",
  expandableCountingFieldsFirst: '(//XCUIElementTypeTextField[starts-with(@name, "expandable_countingFields_")])[1]',
  expandableCountingFieldsSecond: '(//XCUIElementTypeTextField[starts-with(@name, "expandable_countingFields_")])[2]',
  expandableCountingFieldsNth: '(//XCUIElementTypeTextField[starts-with(@name, "expandable_countingFields_")])[{n}]',  // replace {n} with 1-based index
  /** id: expandable_editButton_\(item.id) | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/Components/ExpandableCountItemCard.swift 🆕 NEW */
  expandableEditButton: "-ios predicate string:name BEGINSWITH \"expandable_editButton_\"",
  expandableEditButtonFirst: '(//XCUIElementTypeButton[starts-with(@name, "expandable_editButton_")])[1]',
  expandableEditButtonSecond: '(//XCUIElementTypeButton[starts-with(@name, "expandable_editButton_")])[2]',
  expandableEditButtonNth: '(//XCUIElementTypeButton[starts-with(@name, "expandable_editButton_")])[{n}]',  // replace {n} with 1-based index
  /** id: expandable_header_\(item.id) | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/Components/ExpandableCountItemCard.swift 🆕 NEW */
  expandableHeader: "-ios predicate string:name BEGINSWITH \"expandable_header_\"",
  expandableHeaderFirst: '(//XCUIElementTypeOther[starts-with(@name, "expandable_header_")])[1]',
  expandableHeaderSecond: '(//XCUIElementTypeOther[starts-with(@name, "expandable_header_")])[2]',
  expandableHeaderNth: '(//XCUIElementTypeOther[starts-with(@name, "expandable_header_")])[{n}]',  // replace {n} with 1-based index
  /** id: expandable_item_details_\(item.id) | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/Components/ExpandableCountItemCard.swift 🆕 NEW */
  expandableItemDetails: "-ios predicate string:name BEGINSWITH \"expandable_item_details_\"",
  expandableItemDetailsFirst: '(//XCUIElementTypeOther[starts-with(@name, "expandable_item_details_")])[1]',
  expandableItemDetailsSecond: '(//XCUIElementTypeOther[starts-with(@name, "expandable_item_details_")])[2]',
  expandableItemDetailsNth: '(//XCUIElementTypeOther[starts-with(@name, "expandable_item_details_")])[{n}]',  // replace {n} with 1-based index
  /** id: expandable_item_name_\(item.id) | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/Components/ExpandableCountItemCard.swift 🆕 NEW */
  expandableItemName: "-ios predicate string:name BEGINSWITH \"expandable_item_name_\"",
  expandableItemNameFirst: '(//XCUIElementTypeStaticText[starts-with(@name, "expandable_item_name_")])[1]',
  expandableItemNameSecond: '(//XCUIElementTypeStaticText[starts-with(@name, "expandable_item_name_")])[2]',
  expandableItemNameNth: '(//XCUIElementTypeStaticText[starts-with(@name, "expandable_item_name_")])[{n}]',  // replace {n} with 1-based index
  /** id: expected_count_\(item.id) | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/Components/CountingFieldView.swift 🆕 NEW */
  expectedCount: "-ios predicate string:name BEGINSWITH \"expected_count_\"",
  expectedCountFirst: '(//XCUIElementTypeOther[starts-with(@name, "expected_count_")])[1]',
  expectedCountSecond: '(//XCUIElementTypeOther[starts-with(@name, "expected_count_")])[2]',
  expectedCountNth: '(//XCUIElementTypeOther[starts-with(@name, "expected_count_")])[{n}]',  // replace {n} with 1-based index
  /** id: item_count_\(item.id) | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/Components/CountItemCard.swift 🆕 NEW */
  itemCount: "-ios predicate string:name BEGINSWITH \"item_count_\"",
  itemCountFirst: '(//XCUIElementTypeOther[starts-with(@name, "item_count_")])[1]',
  itemCountSecond: '(//XCUIElementTypeOther[starts-with(@name, "item_count_")])[2]',
  itemCountNth: '(//XCUIElementTypeOther[starts-with(@name, "item_count_")])[{n}]',  // replace {n} with 1-based index
  /** id: modal_title | src: Sources/ToastUnifiedInventory/Shared/UIComponents/SelectCountingStyleView.swift 🆕 NEW */
  modalTitle: "~modal_title",
  /** id: multiUnitSection_\(item.id) | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/Components/CountingFieldView.swift 🆕 NEW */
  multiUnitSection: "-ios predicate string:name BEGINSWITH \"multiUnitSection_\"",
  multiUnitSectionFirst: '(//XCUIElementTypeOther[starts-with(@name, "multiUnitSection_")])[1]',
  multiUnitSectionSecond: '(//XCUIElementTypeOther[starts-with(@name, "multiUnitSection_")])[2]',
  multiUnitSectionNth: '(//XCUIElementTypeOther[starts-with(@name, "multiUnitSection_")])[{n}]',  // replace {n} with 1-based index
  /** id: newBadge_\(countSheet.id) | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/CountSheetScreen.swift 🆕 NEW */
  newBadge: "-ios predicate string:name BEGINSWITH \"newBadge_\"",
  newBadgeFirst: '(//XCUIElementTypeOther[starts-with(@name, "newBadge_")])[1]',
  newBadgeSecond: '(//XCUIElementTypeOther[starts-with(@name, "newBadge_")])[2]',
  newBadgeNth: '(//XCUIElementTypeOther[starts-with(@name, "newBadge_")])[{n}]',  // replace {n} with 1-based index
  /** id: plus_button | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/CountSheetAddItemView.swift 🆕 NEW */
  plusButton: "~plus_button",
  /** id: selectCountSheetView | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/CountSheetScreen.swift 🆕 NEW */
  selectCountSheetView: "~selectCountSheetView",
  /** id: selectedCheckmark_\(countSheet.id) | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/CountSheetScreen.swift 🆕 NEW */
  selectedCheckmark: "-ios predicate string:name BEGINSWITH \"selectedCheckmark_\"",
  selectedCheckmarkFirst: '(//XCUIElementTypeOther[starts-with(@name, "selectedCheckmark_")])[1]',
  selectedCheckmarkSecond: '(//XCUIElementTypeOther[starts-with(@name, "selectedCheckmark_")])[2]',
  selectedCheckmarkNth: '(//XCUIElementTypeOther[starts-with(@name, "selectedCheckmark_")])[{n}]',  // replace {n} with 1-based index
  /** id: selectedCheckmark_\(template.id) | src: Sources/ToastUnifiedInventory/Modules/CycleCount/CountSheetTemplates/Presentation/Views/CountSheetTemplateRow.swift 🆕 NEW */
  selectedCheckmark2: "-ios predicate string:name BEGINSWITH \"selectedCheckmark_\"",
  selectedCheckmark2First: '(//XCUIElementTypeOther[starts-with(@name, "selectedCheckmark_")])[1]',
  selectedCheckmark2Second: '(//XCUIElementTypeOther[starts-with(@name, "selectedCheckmark_")])[2]',
  selectedCheckmark2Nth: '(//XCUIElementTypeOther[starts-with(@name, "selectedCheckmark_")])[{n}]',  // replace {n} with 1-based index
  /** id: selectedUnitLabel_\(item.id) | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/Components/CountingFieldView.swift 🆕 NEW */
  selectedUnitLabel: "-ios predicate string:name BEGINSWITH \"selectedUnitLabel_\"",
  selectedUnitLabelFirst: '(//XCUIElementTypeStaticText[starts-with(@name, "selectedUnitLabel_")])[1]',
  selectedUnitLabelSecond: '(//XCUIElementTypeStaticText[starts-with(@name, "selectedUnitLabel_")])[2]',
  selectedUnitLabelNth: '(//XCUIElementTypeStaticText[starts-with(@name, "selectedUnitLabel_")])[{n}]',  // replace {n} with 1-based index
  /** id: show_all_counts_view | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/CountSheetsItemsView.swift 🆕 NEW */
  showAllCountsView: "~show_all_counts_view",
  /** id: toolbarCancelButton | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/CountSheetScreen.swift 🆕 NEW */
  toolbarCancelButton: "~toolbarCancelButton",
  /** id: toolbarTitle | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/CountSheetScreen.swift 🆕 NEW */
  toolbarTitle: "~toolbarTitle",
  /** id: unitDropdownButton_\(item.id) | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/Components/CountingFieldView.swift 🆕 NEW */
  unitDropdownButton: "-ios predicate string:name BEGINSWITH \"unitDropdownButton_\"",
  unitDropdownButtonFirst: '(//XCUIElementTypeButton[starts-with(@name, "unitDropdownButton_")])[1]',
  unitDropdownButtonSecond: '(//XCUIElementTypeButton[starts-with(@name, "unitDropdownButton_")])[2]',
  unitDropdownButtonNth: '(//XCUIElementTypeButton[starts-with(@name, "unitDropdownButton_")])[{n}]',  // replace {n} with 1-based index
  /** id: unitLabel_\(row.id)_\(item.id) | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/Components/CountingFieldView.swift 🆕 NEW */
  unitLabel: "-ios predicate string:name BEGINSWITH \"unitLabel_\"",
  unitLabelFirst: '(//XCUIElementTypeStaticText[starts-with(@name, "unitLabel_")])[1]',
  unitLabelSecond: '(//XCUIElementTypeStaticText[starts-with(@name, "unitLabel_")])[2]',
  unitLabelNth: '(//XCUIElementTypeStaticText[starts-with(@name, "unitLabel_")])[{n}]',  // replace {n} with 1-based index
  /** id: unitOption_\(unit)_\(item.id) | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/Components/CountingFieldView.swift 🆕 NEW */
  unitOption: "-ios predicate string:name BEGINSWITH \"unitOption_\"",
  unitOptionFirst: '(//XCUIElementTypeOther[starts-with(@name, "unitOption_")])[1]',
  unitOptionSecond: '(//XCUIElementTypeOther[starts-with(@name, "unitOption_")])[2]',
  unitOptionNth: '(//XCUIElementTypeOther[starts-with(@name, "unitOption_")])[{n}]',  // replace {n} with 1-based index

  // ── CycleCount ──────────────────────────────────────────────
  /** id: add_button | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/SearchItemLibraryView.swift 🆕 NEW */
  addButton: "~add_button",
  /** id: back_button | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/Components/CustomNavigationHeader.swift 🆕 NEW */
  backButton: "~back_button",
  /** id: back_spacer | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/Components/CustomNavigationHeader.swift 🆕 NEW */
  backSpacer: "~back_spacer",
  /** id: carousel_edit_button | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/CarouselItemView.swift 🆕 NEW */
  carouselEditButton: "~carousel_edit_button",
  /** id: CountListName | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/CycleCountView.swift 🆕 NEW */
  countListName2: "~CountListName",
  /** id: CountListTemplateBadge | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/CycleCountView.swift 🆕 NEW */
  countListTemplateBadge: "~CountListTemplateBadge",
  /** id: CountSheetNameView | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/CycleCountView.swift 🆕 NEW */
  countSheetNameView: "~CountSheetNameView",
  /** id: InventoryCountsEmptyState | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/CycleCountView.swift 🆕 NEW */
  inventoryCountsEmptyState: "~InventoryCountsEmptyState",
  /** id: item_name_\(item.id) | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/Components/SelectableItemCard.swift 🆕 NEW */
  itemName: "-ios predicate string:name BEGINSWITH \"item_name_\"",
  itemNameFirst: '(//XCUIElementTypeStaticText[starts-with(@name, "item_name_")])[1]',
  itemNameSecond: '(//XCUIElementTypeStaticText[starts-with(@name, "item_name_")])[2]',
  itemNameNth: '(//XCUIElementTypeStaticText[starts-with(@name, "item_name_")])[{n}]',  // replace {n} with 1-based index
  /** id: item_subtitle_\(item.id) | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/Components/SelectableItemCard.swift 🆕 NEW */
  itemSubtitle: "-ios predicate string:name BEGINSWITH \"item_subtitle_\"",
  itemSubtitleFirst: '(//XCUIElementTypeStaticText[starts-with(@name, "item_subtitle_")])[1]',
  itemSubtitleSecond: '(//XCUIElementTypeStaticText[starts-with(@name, "item_subtitle_")])[2]',
  itemSubtitleNth: '(//XCUIElementTypeStaticText[starts-with(@name, "item_subtitle_")])[{n}]',  // replace {n} with 1-based index
  /** id: keyboard_done_button | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/Components/KeyboardToolbar.swift 🆕 NEW */
  keyboardDoneButton: "~keyboard_done_button",
  /** id: library_item_\(item.id) | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/SearchItemLibraryView.swift 🆕 NEW */
  libraryItem: "-ios predicate string:name BEGINSWITH \"library_item_\"",
  libraryItemFirst: '(//XCUIElementTypeOther[starts-with(@name, "library_item_")])[1]',
  libraryItemSecond: '(//XCUIElementTypeOther[starts-with(@name, "library_item_")])[2]',
  libraryItemNth: '(//XCUIElementTypeOther[starts-with(@name, "library_item_")])[{n}]',  // replace {n} with 1-based index
  /** id: offline-display | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/OfflineInfoView.swift 🆕 NEW */
  offlineDisplay: "-ios predicate string:name == \\\"offline-display\\\"",
  /** id: previousCountImage | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/CarouselItemView.swift 🆕 NEW */
  previousCountImage: "~previousCountImage",
  /** id: previousCountText | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/CarouselItemView.swift 🆕 NEW */
  previousCountText: "~previousCountText",
  /** id: previousCountView | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/CarouselItemView.swift 🆕 NEW */
  previousCountView: "~previousCountView",
  /** id: right_buttons_container | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/Components/CustomNavigationHeader.swift 🆕 NEW */
  rightButtonsContainer: "~right_buttons_container",
  /** id: search_button | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/Components/CustomNavigationHeader.swift 🆕 NEW */
  searchButton: "~search_button",
  /** id: settings_button | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/Components/CustomNavigationHeader.swift 🆕 NEW */
  settingsButton: "~settings_button",
  /** id: StartCountingButton | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/CycleCountView.swift 🆕 NEW */
  startCountingButton: "~StartCountingButton",
  /** id: StartCountingButtonLoading | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/CycleCountView.swift 🆕 NEW */
  startCountingButtonLoading: "~StartCountingButtonLoading",
  /** id: subtitle_text | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/Components/CustomNavigationHeader.swift 🆕 NEW */
  subtitleText: "~subtitle_text",
  /** id: title_section | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/Components/CustomNavigationHeader.swift 🆕 NEW */
  titleSection: "~title_section",
  /** id: title_text | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/Components/CustomNavigationHeader.swift 🆕 NEW */
  titleText: "~title_text",
  /** id: wifi_button | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/Components/CustomNavigationHeader.swift 🆕 NEW */
  wifiButton: "~wifi_button",
  /** id: wifi_spacer | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/Components/CustomNavigationHeader.swift 🆕 NEW */
  wifiSpacer: "~wifi_spacer",
  /** id: working-offline-content | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/OfflineInfoView.swift 🆕 NEW */
  workingOfflineContent: "-ios predicate string:name == \\\"working-offline-content\\\"",
  /** id: working-offline-title | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/OfflineInfoView.swift 🆕 NEW */
  workingOfflineTitle: "-ios predicate string:name == \\\"working-offline-title\\\"",

  // ── Home ──────────────────────────────────────────────
  /** id: SuggestedOrdersEmptyState | src: Sources/ToastUnifiedInventory/Modules/SuggestedOrder/Presentation/Views/SuggestedOrderHomeView.swift 🆕 NEW */
  suggestedOrdersEmptyState: "~SuggestedOrdersEmptyState",

  // ── Invoice ──────────────────────────────────────────────
  /** id: invoice_management_list | src: Sources/ToastUnifiedInventory/Modules/InvoiceScanning/Presentation/Views/InvoiceManagementView.swift 🆕 NEW */
  invoiceManagementList: "~invoice_management_list",
  /** id: invoice_pre_management_submit | src: Sources/ToastUnifiedInventory/Modules/InvoiceScanning/Presentation/Views/InvoicePreManagementView.swift 🆕 NEW */
  invoicePreManagementSubmit: "~invoice_pre_management_submit",
  /** id: invoice_preview_next | src: Sources/ToastUnifiedInventory/Modules/InvoiceScanning/Presentation/Views/InvoicePreviewView.swift 🆕 NEW */
  invoicePreviewNext: "~invoice_preview_next",

  // ── Location ──────────────────────────────────────────────
  /** id: close_button | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/AddItemLocationView.swift 🆕 NEW */
  closeButton: "~close_button",
  /** id: internal_notes_input | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/AddItemLocationView.swift 🆕 NEW */
  internalNotesInput: "~internal_notes_input",
  /** id: internal_notes_label | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/AddItemLocationView.swift 🆕 NEW */
  internalNotesLabel: "~internal_notes_label",
  /** id: location_card_\(location.id) | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/Components/LocationCard.swift 🆕 NEW */
  locationCard: "-ios predicate string:name BEGINSWITH \"location_card_\"",
  locationCardFirst: '(//XCUIElementTypeOther[starts-with(@name, "location_card_")])[1]',
  locationCardSecond: '(//XCUIElementTypeOther[starts-with(@name, "location_card_")])[2]',
  locationCardNth: '(//XCUIElementTypeOther[starts-with(@name, "location_card_")])[{n}]',  // replace {n} with 1-based index
  /** id: location_chevron_\(location.id) | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/Components/LocationCard.swift 🆕 NEW */
  locationChevron: "-ios predicate string:name BEGINSWITH \"location_chevron_\"",
  locationChevronFirst: '(//XCUIElementTypeImage[starts-with(@name, "location_chevron_")])[1]',
  locationChevronSecond: '(//XCUIElementTypeImage[starts-with(@name, "location_chevron_")])[2]',
  locationChevronNth: '(//XCUIElementTypeImage[starts-with(@name, "location_chevron_")])[{n}]',  // replace {n} with 1-based index
  /** id: location_count_\(location.id) | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/Components/LocationCard.swift 🆕 NEW */
  locationCount: "-ios predicate string:name BEGINSWITH \"location_count_\"",
  locationCountFirst: '(//XCUIElementTypeOther[starts-with(@name, "location_count_")])[1]',
  locationCountSecond: '(//XCUIElementTypeOther[starts-with(@name, "location_count_")])[2]',
  locationCountNth: '(//XCUIElementTypeOther[starts-with(@name, "location_count_")])[{n}]',  // replace {n} with 1-based index
  /** id: location_name_\(location.id) | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/Components/LocationCard.swift 🆕 NEW */
  locationName: "-ios predicate string:name BEGINSWITH \"location_name_\"",
  locationNameFirst: '(//XCUIElementTypeStaticText[starts-with(@name, "location_name_")])[1]',
  locationNameSecond: '(//XCUIElementTypeStaticText[starts-with(@name, "location_name_")])[2]',
  locationNameNth: '(//XCUIElementTypeStaticText[starts-with(@name, "location_name_")])[{n}]',  // replace {n} with 1-based index
  /** id: location_name_input | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/AddItemLocationView.swift 🆕 NEW */
  locationNameInput: "~location_name_input",
  /** id: location_name_label | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/AddItemLocationView.swift 🆕 NEW */
  locationNameLabel: "~location_name_label",
  /** id: location_type_\(type == .shelfVisibleToCustomer ?  | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/AddItemLocationView.swift 🆕 NEW */
  locationTypeTypeShelfVisibleToCustomer: "-ios predicate string:name BEGINSWITH \"location_type_\"",
  locationTypeTypeShelfVisibleToCustomerFirst: '(//XCUIElementTypeOther[starts-with(@name, "location_type_")])[1]',
  locationTypeTypeShelfVisibleToCustomerSecond: '(//XCUIElementTypeOther[starts-with(@name, "location_type_")])[2]',
  locationTypeTypeShelfVisibleToCustomerNth: '(//XCUIElementTypeOther[starts-with(@name, "location_type_")])[{n}]',  // replace {n} with 1-based index
  /** id: location_type_label | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/AddItemLocationView.swift 🆕 NEW */
  locationTypeLabel: "~location_type_label",
  /** id: save_button | src: Sources/ToastUnifiedInventory/Modules/CycleCount/Presentation/Views/AddItemLocationView.swift 🆕 NEW */
  saveButton: "~save_button",

  // ── ProductCatalog ──────────────────────────────────────────────
  /** id: \(viewModel.context.screenTitle)-title | src: Sources/ToastUnifiedInventory/Modules/ProductCatalog/Presentation/Views/ProductItemDetailView.swift 🆕 NEW */
  title2: "// dynamic: \\(viewModel.context.screenTitle)-title",
  /** id: add_product_button | src: Sources/ToastUnifiedInventory/Modules/ProductCatalog/Presentation/Views/ProductCatalogSearchView.swift 🆕 NEW */
  addProductButton: "~add_product_button",
  /** id: clear_search_button | src: Sources/ToastUnifiedInventory/Modules/ProductCatalog/Presentation/Views/ProductCatalogSearchView.swift 🆕 NEW */
  clearSearchButton: "~clear_search_button",
  /** id: item_\(field.accessibilityIdentifier) | src: Sources/ToastUnifiedInventory/Shared/UIComponents/ProductCatalogItemRow.swift 🆕 NEW */
  item: "-ios predicate string:name BEGINSWITH \"item_\"",
  itemFirst: '(//XCUIElementTypeOther[starts-with(@name, "item_")])[1]',
  itemSecond: '(//XCUIElementTypeOther[starts-with(@name, "item_")])[2]',
  itemNth: '(//XCUIElementTypeOther[starts-with(@name, "item_")])[{n}]',  // replace {n} with 1-based index
  /** id: item_edit | src: Sources/ToastUnifiedInventory/Shared/UIComponents/ProductCatalogItemRow.swift 🆕 NEW */
  itemEdit: "~item_edit",
  /** id: item_thumbnail | src: Sources/ToastUnifiedInventory/Shared/UIComponents/ProductCatalogListThumbnailView.swift 🆕 NEW */
  itemThumbnail: "~item_thumbnail",
  /** id: item_variant_chevron | src: Sources/ToastUnifiedInventory/Modules/ProductCatalog/Presentation/Views/ProductVariantCardView.swift 🆕 NEW */
  itemVariantChevron: "~item_variant_chevron",
  /** id: item_viewDetails | src: Sources/ToastUnifiedInventory/Shared/UIComponents/ProductCatalogItemRow.swift 🆕 NEW */
  itemViewDetails: "~item_viewDetails",
  /** id: primary_button | src: Sources/ToastUnifiedInventory/Modules/ProductCatalog/Presentation/Views/ProductItemDetailView.swift 🆕 NEW */
  primaryButton: "~primary_button",
  /** id: product_catalog_addButton | src: Sources/ToastUnifiedInventory/Modules/ProductCatalog/Presentation/Views/ProductCatalogView.swift 🆕 NEW */
  productCatalogAddButton: "~product_catalog_addButton",
  /** id: product_catalog_filter_sort_sheet_category_section | src: Sources/ToastUnifiedInventory/Modules/ProductCatalog/Presentation/Views/ProductCatalogFilterSortSheet.swift 🆕 NEW */
  productCatalogFilterSortSheetCategorySection: "~product_catalog_filter_sort_sheet_category_section",
  /** id: product_catalog_filter_sort_sheet_sort_by_section | src: Sources/ToastUnifiedInventory/Modules/ProductCatalog/Presentation/Views/ProductCatalogFilterSortSheet.swift 🆕 NEW */
  productCatalogFilterSortSheetSortBySection: "~product_catalog_filter_sort_sheet_sort_by_section",
  /** id: product_catalog_filter_sort_sheet_vendor_section | src: Sources/ToastUnifiedInventory/Modules/ProductCatalog/Presentation/Views/ProductCatalogFilterSortSheet.swift 🆕 NEW */
  productCatalogFilterSortSheetVendorSection: "~product_catalog_filter_sort_sheet_vendor_section",
  /** id: product_catalog_filter_sort_sheet_view_button | src: Sources/ToastUnifiedInventory/Modules/ProductCatalog/Presentation/Views/ProductCatalogFilterSortSheet.swift 🆕 NEW */
  productCatalogFilterSortSheetViewButton: "~product_catalog_filter_sort_sheet_view_button",
  /** id: product_catalog_filter_sort_sheet_warnings_and_info_section | src: Sources/ToastUnifiedInventory/Modules/ProductCatalog/Presentation/Views/ProductCatalogFilterSortSheet.swift 🆕 NEW */
  productCatalogFilterSortSheetWarningsAndInfoSection: "~product_catalog_filter_sort_sheet_warnings_and_info_section",
  /** id: product_catalog_header | src: Sources/ToastUnifiedInventory/Modules/ProductCatalog/Presentation/Views/ProductCatalogPreviewView.swift 🆕 NEW */
  productCatalogHeader: "~product_catalog_header",
  /** id: product_catalog_item_\(item.id) | src: Sources/ToastUnifiedInventory/Shared/UIComponents/ProductCatalogItemRow.swift 🆕 NEW */
  productCatalogItem: "-ios predicate string:name BEGINSWITH \"product_catalog_item_\"",
  productCatalogItemFirst: '(//XCUIElementTypeOther[starts-with(@name, "product_catalog_item_")])[1]',
  productCatalogItemSecond: '(//XCUIElementTypeOther[starts-with(@name, "product_catalog_item_")])[2]',
  productCatalogItemNth: '(//XCUIElementTypeOther[starts-with(@name, "product_catalog_item_")])[{n}]',  // replace {n} with 1-based index
  /** id: product_catalog_item_chevron | src: Sources/ToastUnifiedInventory/Shared/UIComponents/ProductCatalogItemRow.swift 🆕 NEW */
  productCatalogItemChevron: "~product_catalog_item_chevron",
  /** id: product_catalog_items | src: Sources/ToastUnifiedInventory/Modules/ProductCatalog/Presentation/Views/ProductCatalogPreviewView.swift 🆕 NEW */
  productCatalogItems: "~product_catalog_items",
  /** id: product_catalog_preview | src: Sources/ToastUnifiedInventory/Modules/ProductCatalog/Presentation/Views/ProductCatalogPreviewView.swift 🆕 NEW */
  productCatalogPreview: "~product_catalog_preview",
  /** id: product_catalog_title_\(item.id) | src: Sources/ToastUnifiedInventory/Shared/UIComponents/ProductCatalogItemRow.swift 🆕 NEW */
  productCatalogTitle: "-ios predicate string:name BEGINSWITH \"product_catalog_title_\"",
  productCatalogTitleFirst: '(//XCUIElementTypeStaticText[starts-with(@name, "product_catalog_title_")])[1]',
  productCatalogTitleSecond: '(//XCUIElementTypeStaticText[starts-with(@name, "product_catalog_title_")])[2]',
  productCatalogTitleNth: '(//XCUIElementTypeStaticText[starts-with(@name, "product_catalog_title_")])[{n}]',  // replace {n} with 1-based index
  /** id: product_detail_edit_button | src: Sources/ToastUnifiedInventory/Modules/ProductCatalog/Presentation/Views/ProductDetailView.swift 🆕 NEW */
  productDetailEditButton: "~product_detail_edit_button",
  /** id: product_detail_overflow_button | src: Sources/ToastUnifiedInventory/Modules/ProductCatalog/Presentation/Views/ProductDetailView.swift 🆕 NEW */
  productDetailOverflowButton: "~product_detail_overflow_button",
  /** id: product_detail_product_name | src: Sources/ToastUnifiedInventory/Modules/ProductCatalog/Presentation/Views/ProductDetailView.swift 🆕 NEW */
  productDetailProductName: "~product_detail_product_name",
  /** id: product_detail_unavailable_banner | src: Sources/ToastUnifiedInventory/Modules/ProductCatalog/Presentation/Views/ProductDetailView.swift 🆕 NEW */
  productDetailUnavailableBanner: "~product_detail_unavailable_banner",
  /** id: product_details_setting_container | src: Sources/ToastUnifiedInventory/Modules/ProductCatalog/Presentation/Views/ProductCatalogDetailsSettingsView.swift 🆕 NEW */
  productDetailsSettingContainer: "~product_details_setting_container",
  /** id: product_item_\(item.id) | src: Sources/ToastUnifiedInventory/Modules/ProductCatalog/Presentation/Views/ProductCatalogPreviewView.swift 🆕 NEW */
  productItem: "-ios predicate string:name BEGINSWITH \"product_item_\"",
  productItemFirst: '(//XCUIElementTypeOther[starts-with(@name, "product_item_")])[1]',
  productItemSecond: '(//XCUIElementTypeOther[starts-with(@name, "product_item_")])[2]',
  productItemNth: '(//XCUIElementTypeOther[starts-with(@name, "product_item_")])[{n}]',  // replace {n} with 1-based index
  /** id: product_variant_item_\(item.id) | src: Sources/ToastUnifiedInventory/Modules/ProductCatalog/Presentation/Views/ProductVariantCardView.swift 🆕 NEW */
  productVariantItem: "-ios predicate string:name BEGINSWITH \"product_variant_item_\"",
  productVariantItemFirst: '(//XCUIElementTypeOther[starts-with(@name, "product_variant_item_")])[1]',
  productVariantItemSecond: '(//XCUIElementTypeOther[starts-with(@name, "product_variant_item_")])[2]',
  productVariantItemNth: '(//XCUIElementTypeOther[starts-with(@name, "product_variant_item_")])[{n}]',  // replace {n} with 1-based index
  /** id: productCatalogSearchBar | src: Sources/ToastUnifiedInventory/Modules/ProductCatalog/Presentation/Views/ProductCatalogSearchBar.swift 🆕 NEW */
  productCatalogSearchBar: "~productCatalogSearchBar",
  /** id: remove-variant-group-from-list-button | src: Sources/ToastUnifiedInventory/Modules/ProductCatalog/Presentation/Views/ProductItemDetailView.swift 🆕 NEW */
  removeVariantGroupFromListButton: "-ios predicate string:name == \\\"remove-variant-group-from-list-button\\\"",
  /** id: view_all_button | src: Sources/ToastUnifiedInventory/Modules/ProductCatalog/Presentation/Views/ProductCatalogPreviewView.swift 🆕 NEW */
  viewAllButton: "~view_all_button",

  // ── Shared ──────────────────────────────────────────────
  /** id: \(fieldId)_dropdown | src: Sources/ToastUnifiedInventory/Shared/UIComponents/FormFields/DropdownFieldView.swift 🆕 NEW */
  dropdown: "// dynamic: \\(fieldId)_dropdown",
  /** id: \(fieldId)_error | src: Sources/ToastUnifiedInventory/Shared/UIComponents/FormFields/NumberInputFieldView.swift 🆕 NEW */
  error: "// dynamic: \\(fieldId)_error",
  /** id: \(fieldId)_input | src: Sources/ToastUnifiedInventory/Shared/UIComponents/FormFields/TextInputFieldView.swift 🆕 NEW */
  input: "// dynamic: \\(fieldId)_input",
  /** id: \(fieldId)_label | src: Sources/ToastUnifiedInventory/Shared/UIComponents/FormFields/TextInputFieldView.swift 🆕 NEW */
  label: "// dynamic: \\(fieldId)_label",
  /** id: \(iconType) | src: Sources/ToastUnifiedInventory/Shared/UIComponents/ConfirmationPopupView.swift 🆕 NEW */
  unknown: "// dynamic: \\(iconType)",
  /** id: \(imageAccessibilityIdentifier ??  | src: Sources/ToastUnifiedInventory/Shared/UIComponents/EmptyStateView.swift 🆕 NEW */
  imageAccessibilityIdentifier: "// dynamic: \\(imageAccessibilityIdentifier ?? ",
  /** id: \(textAccessibilityIdentifier ??  | src: Sources/ToastUnifiedInventory/Shared/UIComponents/EmptyStateView.swift 🆕 NEW */
  textAccessibilityIdentifier: "// dynamic: \\(textAccessibilityIdentifier ?? ",
  /** id: \(title)-subtitle | src: Sources/ToastUnifiedInventory/Shared/UIComponents/SelectOptionSheetView.swift 🆕 NEW */
  subtitle: "// dynamic: \\(title)-subtitle",
  /** id: \(title)-title | src: Sources/ToastUnifiedInventory/Shared/UIComponents/SelectOptionSheetView.swift 🆕 NEW */
  title: "// dynamic: \\(title)-title",
  /** id: BannerView | src: Sources/ToastUnifiedInventory/Shared/UIComponents/BannerView.swift 🆕 NEW */
  bannerView: "~BannerView",
  /** id: barcodeScannerButton | src: Sources/ToastUnifiedInventory/Shared/UIComponents/SearchBarWithCancel.swift 🆕 NEW */
  barcodeScannerButton: "~barcodeScannerButton",
  /** id: cancel-button | src: Sources/ToastUnifiedInventory/Shared/UIComponents/SelectOptionSheetView.swift 🆕 NEW */
  cancelButton2: "-ios predicate string:name == \\\"cancel-button\\\"",
  /** id: cancelButton | src: Sources/ToastUnifiedInventory/Shared/UIComponents/SearchBarWithCancel.swift 🆕 NEW */
  cancelButton3: "~cancelButton",
  /** id: closeButton | src: Sources/ToastUnifiedInventory/Shared/UIComponents/ConfirmationPopupView.swift 🆕 NEW */
  closeButton2: "~closeButton",
  /** id: confirmation_popup_primary_button | src: Sources/ToastUnifiedInventory/Shared/UIComponents/ConfirmationPopupView.swift 🆕 NEW */
  confirmationPopupPrimaryButton: "~confirmation_popup_primary_button",
  /** id: confirmation_popup_secondary_button | src: Sources/ToastUnifiedInventory/Shared/UIComponents/ConfirmationPopupView.swift 🆕 NEW */
  confirmationPopupSecondaryButton: "~confirmation_popup_secondary_button",
  /** id: countListDropdown | src: Sources/ToastUnifiedInventory/Shared/Views/PostSubmissionView.swift 🆕 NEW */
  countListDropdown: "~countListDropdown",
  /** id: countListName | src: Sources/ToastUnifiedInventory/Shared/Views/PostSubmissionView.swift 🆕 NEW */
  countListName: "~countListName",
  /** id: emptyStateViewSubText | src: Sources/ToastUnifiedInventory/Shared/UIComponents/EmptyStateView.swift 🆕 NEW */
  emptyStateViewSubText: "~emptyStateViewSubText",
  /** id: infoText | src: Sources/ToastUnifiedInventory/Shared/UIComponents/InfoCardView.swift 🆕 NEW */
  infoText: "~infoText",
  /** id: invalid_check_digit_barcode_modal | src: Sources/ToastUnifiedInventory/Shared/UIComponents/InvalidCheckDigitSaveModalOverlay.swift 🆕 NEW */
  invalidCheckDigitBarcodeModal: "~invalid_check_digit_barcode_modal",
  /** id: invoice_capture_close | src: Sources/ToastUnifiedInventory/Shared/Scanner/ScanbotScanner/DocumentScanner/DocumentScannerOverlayView.swift 🆕 NEW */
  invoiceCaptureClose: "~invoice_capture_close",
  /** id: invoice_submitted_success_title | src: Sources/ToastUnifiedInventory/Shared/Views/PostSubmissionView.swift 🆕 NEW */
  invoiceSubmittedSuccessTitle: "~invoice_submitted_success_title",
  /** id: invoiceSavedOfflineSubtitle | src: Sources/ToastUnifiedInventory/Shared/Views/PostSubmissionView.swift 🆕 NEW */
  invoiceSavedOfflineSubtitle: "~invoiceSavedOfflineSubtitle",
  /** id: invoiceSavedOfflineSuccessIcon | src: Sources/ToastUnifiedInventory/Shared/Views/PostSubmissionView.swift 🆕 NEW */
  invoiceSavedOfflineSuccessIcon: "~invoiceSavedOfflineSuccessIcon",
  /** id: invoiceSavedOfflineTitle | src: Sources/ToastUnifiedInventory/Shared/Views/PostSubmissionView.swift 🆕 NEW */
  invoiceSavedOfflineTitle: "~invoiceSavedOfflineTitle",
  /** id: nextCountListName | src: Sources/ToastUnifiedInventory/Shared/Views/PostSubmissionView.swift 🆕 NEW */
  nextCountListName: "~nextCountListName",
  /** id: no-search-results-image | src: Sources/ToastUnifiedInventory/Shared/UIComponents/SelectOptionSheetView.swift 🆕 NEW */
  noSearchResultsImage: "-ios predicate string:name == \\\"no-search-results-image\\\"",
  /** id: no-search-results-sub-text | src: Sources/ToastUnifiedInventory/Shared/UIComponents/SelectOptionSheetView.swift 🆕 NEW */
  noSearchResultsSubText: "-ios predicate string:name == \\\"no-search-results-sub-text\\\"",
  /** id: no-search-results-text | src: Sources/ToastUnifiedInventory/Shared/UIComponents/SelectOptionSheetView.swift 🆕 NEW */
  noSearchResultsText: "-ios predicate string:name == \\\"no-search-results-text\\\"",
  /** id: primary-button | src: Sources/ToastUnifiedInventory/Shared/UIComponents/SubmitButtonGroupView.swift 🆕 NEW */
  primaryButton2: "-ios predicate string:name == \\\"primary-button\\\"",
  /** id: save-button | src: Sources/ToastUnifiedInventory/Shared/UIComponents/SelectOptionSheetView.swift 🆕 NEW */
  saveButton2: "-ios predicate string:name == \\\"save-button\\\"",
  /** id: searchClearButton | src: Sources/ToastUnifiedInventory/Shared/UIComponents/SearchBarWithCancel.swift 🆕 NEW */
  searchClearButton: "~searchClearButton",
  /** id: searchTextField | src: Sources/ToastUnifiedInventory/Shared/UIComponents/SearchBarWithCancel.swift 🆕 NEW */
  searchTextField: "~searchTextField",
  /** id: secondary_button | src: Sources/ToastUnifiedInventory/Shared/UIComponents/SelectOptionSheetView.swift 🆕 NEW */
  secondaryButton: "~secondary_button",
  /** id: secondary-button | src: Sources/ToastUnifiedInventory/Shared/UIComponents/SubmitButtonGroupView.swift 🆕 NEW */
  secondaryButton2: "-ios predicate string:name == \\\"secondary-button\\\"",
  /** id: startCountButton | src: Sources/ToastUnifiedInventory/Shared/Views/PostSubmissionView.swift 🆕 NEW */
  startCountButton: "~startCountButton",
  /** id: statusImage | src: Sources/ToastUnifiedInventory/Shared/UIComponents/BannerView.swift 🆕 NEW */
  statusImage: "~statusImage",
  /** id: styledText | src: Sources/ToastUnifiedInventory/Shared/UIComponents/BannerView.swift 🆕 NEW */
  styledText: "~styledText",
  /** id: submit_button | src: Sources/ToastUnifiedInventory/Shared/UIComponents/SubmitButtonGroupView.swift 🆕 NEW */
  submitButton: "~submit_button",
  /** id: submittedByText | src: Sources/ToastUnifiedInventory/Shared/Views/PostSubmissionView.swift 🆕 NEW */
  submittedByText: "~submittedByText",
  /** id: submittedCard | src: Sources/ToastUnifiedInventory/Shared/Views/PostSubmissionView.swift 🆕 NEW */
  submittedCard: "~submittedCard",
  /** id: successCheckmark | src: Sources/ToastUnifiedInventory/Shared/Views/PostSubmissionView.swift 🆕 NEW */
  successCheckmark: "~successCheckmark",
  /** id: thankYouTitle | src: Sources/ToastUnifiedInventory/Shared/Views/PostSubmissionView.swift 🆕 NEW */
  thankYouTitle: "~thankYouTitle",
  /** id: toolbar_back_button | src: Sources/ToastUnifiedInventory/Shared/UIComponents/CustomToolbar.swift 🆕 NEW */
  toolbarBackButton: "~toolbar_back_button",
  /** id: toolbar_subtitle_text | src: Sources/ToastUnifiedInventory/Shared/UIComponents/CustomToolbar.swift 🆕 NEW */
  toolbarSubtitleText: "~toolbar_subtitle_text",
  /** id: toolbar_title_section | src: Sources/ToastUnifiedInventory/Shared/UIComponents/CustomToolbar.swift 🆕 NEW */
  toolbarTitleSection: "~toolbar_title_section",
  /** id: toolbar_title_text | src: Sources/ToastUnifiedInventory/Shared/UIComponents/CustomToolbar.swift 🆕 NEW */
  toolbarTitleText: "~toolbar_title_text",
  /** id: toolbar_wifi_button | src: Sources/ToastUnifiedInventory/Shared/UIComponents/CustomToolbar.swift 🆕 NEW */
  toolbarWifiButton: "~toolbar_wifi_button",
  /** id: unscannable_barcode_modal | src: Sources/ToastUnifiedInventory/Shared/UIComponents/UnscannableBarcodeSaveModalOverlay.swift 🆕 NEW */
  unscannableBarcodeModal: "~unscannable_barcode_modal",
  /** id: upNextLabel | src: Sources/ToastUnifiedInventory/Shared/Views/PostSubmissionView.swift 🆕 NEW */
  upNextLabel: "~upNextLabel",
} as const;

export type GLKey = keyof typeof GL;
